import './globals.css'
import { Inter } from 'next/font/google'
import Link from "next/link"
import LoginBtn from "./LoginBtn.js"
import LogOutBtn from "./LogOutBtn.js"
import { authOptions } from "@/pages/api/auth/[...nextauth].js"
import { getServerSession } from "next-auth"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Mok first next js page',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="navbar"> 
        <Link href="/" className="logo">Test board</Link> 
        <Link href="/list">| List |</Link> 
        <Link href="/write">| Write |</Link> 
        { 
        session 
        ? <span className='login_info'> User: {session.user.name} <LogOutBtn/> </span> 
        : <LoginBtn></LoginBtn>
        }
        <Link href="/register">| Register |</Link> 
      </div>  
        {children}</body>
    </html>
  )
}
